<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blogs = [
            ["user_id" => 1, "title" => "2024 Yılında Elektrikli Arabalar", "content" => "Elektrikli arabalar son birkaç yılda hızla popülerlik kazandı. Tesla, Nissan ve Volkswagen gibi önde gelen üreticilerin yeni modelleri ile pazar daha çevreci alternatiflere yöneliyor. 2024 yılında, daha fazla elektrikli araç şarj istasyonu, daha hızlı şarj süreleri ve daha uzun pil ömrüne sahip arabalar görüyoruz. Bu gelişmeler, elektrikli arabaları günlük kullanım için, hatta uzun yolculuklar için bile daha pratik hale getiriyor.", "media" => "blog1.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 2, "title" => "Aileler İçin En İyi SUV Modelleri", "content" => "Aile arabaları söz konusu olduğunda, SUV\'lar geniş iç mekanları ve güvenlik özellikleri ile öne çıkıyor. 2024 yılında Toyota Highlander, Honda Pilot ve Ford Explorer gibi modeller bu alanlarda mükemmelleşiyor. Bu araçların her biri, üç sıra koltuk, bol miktarda bagaj alanı ve en son güvenlik teknolojilerini sunuyor. Ayrıca, birçok model artık hibrit veya elektrikli seçeneklerle geliyor ve bu da onları daha yakıt tasarruflu hale getiriyor.", "media" => "blog2.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 3, "title" => "Otonom Araçların Geleceği", "content" => "Otonom araçlar ya da sürücüsüz arabalar, yıllardır ilgi çekici bir konu. 2024 yılında, bu araçları yollarda görmeye daha da yaklaşıyoruz. Waymo ve Tesla gibi şirketler bu teknolojide liderlik yaparken, otonom sürüşün arkasındaki teknoloji giderek daha güvenilir ve emniyetli hale geliyor. Gelecek, trafik kazalarını azaltma, trafik sıkışıklığını hafifletme ve sürüş yapamayanlar için yeni mobilite seçenekleri sunma vaatleri taşıyor.", "media" => "blog3.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 4, "title" => "Hibrit Arabalar Neden Hala Geçerli?", "content" => "Tam elektrikli arabalar son zamanlarda daha fazla ilgi görse de, hibrit arabalar birçok sürücü için hala akıllı bir tercih olmaya devam ediyor. Hibrit arabalar, benzin motorunu elektrik motoru ile birleştirerek her iki dünyanın en iyisini sunuyor. 2024 yılında Toyota Prius ve Honda Insight gibi hibritler, özellikle şehir içi trafikte mükemmel yakıt verimliliği sağlıyor. Elektrikli araçlara tam anlamıyla geçiş yapmak istemeyenler için harika bir seçenek.", "media" => "blog4.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 5, "title" => "50.000 Doların Altındaki En İyi 5 Spor Araba", "content" => "Bir spor araba sahibi olmak bütçenizi zorlamak zorunda değil. 2024 yılında, birkaç uygun fiyatlı model hem hız hem de stil sunuyor. Ford Mustang, Chevrolet Camaro ve Subaru BRZ, 50.000 doların altında harika performans sunan spor arabalara sadece birkaç örnek. İster güç, ister yol tutuşu, ister sadece şık bir tasarım arıyor olun, bu arabalar uygun fiyata heyecan verici bir sürüş deneyimi sunuyor.", "media" => "blog5.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 6, "title" => "Kışın Arabanızı Nasıl Korursunuz?", "content" => "Kış mevsimi, özellikle yoğun kar ve buz olan bölgelerde arabalar için zorlu olabilir. Arabanızın en iyi durumda kalması için, soğuk hava gelmeden önce kışa hazırlık yapmanız önemlidir. Lastiklerinizi kontrol edin, uygun diş derinliğine sahip olduklarından emin olun ve kış lastiklerine geçmeyi düşünün. Ayrıca, arabanızın aküsünü kontrol edin, çünkü soğuk hava akünün verimliliğini azaltabilir. Antifriz seviyelerinizi kontrol etmeyi ve sileceklerinizi kar ve buz için uygun hale getirmeyi unutmayın.", "media" => "blog6.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 7, "title" => "Araba Tasarımının Evrimi", "content" => "Araba tasarımı 1900\'lü yıllardan bu yana uzun bir yol kat etti. Model T\'nin köşeli şekillerinden bugünün şık, aerodinamik tasarımlarına kadar her on yılda arabaların görünümü büyük değişiklikler geçirdi. 2024 yılında, verimlilik ve sürdürülebilirliği ön planda tutan tasarımlar görüyoruz. Birçok araba, daha hafif malzemeler ve geliştirilmiş aerodinamik özellikler içeriyor. Özellikle elektrikli araçlar, motor ve yakıt tankları için daha az alana ihtiyaç duyduklarından tasarımda yeni trendler yaratıyor.", "media" => "blog7.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 8, "title" => "2024 Yılının En Yakıt Verimli Arabaları", "content" => "Yükselen yakıt fiyatları ve çevresel endişelerle birlikte, yakıt verimliliği birçok otomobil alıcısı için her zamankinden daha önemli hale geldi. 2024 yılında Toyota Corolla Hybrid, Honda Accord Hybrid ve Hyundai Ioniq gibi arabalar yakıt verimliliğinde öncülük ediyor. Bu arabalar 50 milin üzerinde galon başına yol yaparak, hem yakıt masraflarını azaltmak hem de karbon ayak izini düşürmek isteyenler için mükemmel seçenekler sunuyor. Ayrıca, bu modellerin birçoğu en son teknoloji ve özelliklerle birlikte geliyor.", "media" => "blog8.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 9, "title" => "Elektrikli vs Hibrit: Hangisi Daha İyi?", "content" => "Elektrikli ve hibrit arabalar arasında seçim yaparken dikkate alınması gereken birkaç faktör var. Tesla Model 3 gibi elektrikli arabalar tamamen elektrikle çalışır ve hiç emisyon üretmez. Ancak, şarj altyapısına bağımlıdırlar ve sınırlı menzile sahip olabilirler. Toyota Prius gibi hibritler ise hem benzin hem de elektrik kullanarak, verimlilik ve pratiklik arasında bir denge sunar. 2024 yılında seçim, sürüş alışkanlıklarınıza ve şarj istasyonlarına erişiminize bağlı olarak değişir.", "media" => "blog9.jpg", "created_at" => now(), "updated_at" => now()],
            ["user_id" => 10, "title" => "Elektrikli Kamyonların Yükselişi", "content" => "Elektrikli kamyonlar, otomotiv pazarında ciddi bir rakip haline geliyor. 2024 yılında Rivian R1T ve Ford F-150 Lightning gibi modeller, etkileyici performansları ve çevre dostu özellikleri ile manşetlere çıkıyor. Elektrikli kamyonlar, geleneksel kamyonların gücü ve kapasitesini sunarken emisyonları azaltıyor. Pil teknolojisindeki gelişmeler sayesinde bu kamyonlar, hem iş hem de eğlence amaçlı kullanım için gerekli olan menzil ve çekme kapasitesine artık sahip.", "media" => "blog10.jpg", "created_at" => now(), "updated_at" => now()],
        ];

        DB::table('blogs')->insert($blogs);
    }
}
