<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $models = [
            ["brand_id" => 1, "name" => "Megane"],
            ["brand_id" => 1, "name" => "Clio"],
            ["brand_id" => 1, "name" => "Captur"],
            ["brand_id" => 1, "name" => "Taliant"],
            ["brand_id" => 1, "name" => "Talisman"],
            ["brand_id" => 1, "name" => "Austral"],
            ["brand_id" => 1, "name" => "Fluence"],
            ["brand_id" => 1, "name" => "Symbol"],
            ["brand_id" => 1, "name" => "Zoe"],
            ["brand_id" => 1, "name" => "Twingo"],
            ["brand_id" => 2, "name" => "Linea"],
            ["brand_id" => 2, "name" => "Egea"],
            ["brand_id" => 2, "name" => "Punto"],
            ["brand_id" => 2, "name" => "Albea"],
            ["brand_id" => 2, "name" => "Palio"],
            ["brand_id" => 2, "name" => "Doblo"],
            ["brand_id" => 2, "name" => "Fiorino"],
            ["brand_id" => 2, "name" => "500L"],
            ["brand_id" => 2, "name" => "Tipo"],
            ["brand_id" => 2, "name" => "Uno"],
            ["brand_id" => 3, "name" => "Golf"],
            ["brand_id" => 3, "name" => "Polo"],
            ["brand_id" => 3, "name" => "Passat"],
            ["brand_id" => 3, "name" => "Jetta"],
            ["brand_id" => 3, "name" => "Tiguan"],
            ["brand_id" => 3, "name" => "Amarok"],
            ["brand_id" => 3, "name" => "Caddy"],
            ["brand_id" => 3, "name" => "Scirocco"],
            ["brand_id" => 3, "name" => "T-Roc"],
            ["brand_id" => 3, "name" => "Beetle"],
            ["brand_id" => 4, "name" => "Corsa"],
            ["brand_id" => 4, "name" => "Astra"],
            ["brand_id" => 4, "name" => "Insignia"],
            ["brand_id" => 4, "name" => "Crossland"],
            ["brand_id" => 4, "name" => "Grandland"],
            ["brand_id" => 4, "name" => "Combo"],
            ["brand_id" => 4, "name" => "Mokka"],
            ["brand_id" => 4, "name" => "Zafira"],
            ["brand_id" => 4, "name" => "Adam"],
            ["brand_id" => 4, "name" => "Meriva"],
            ["brand_id" => 5, "name" => "Elantra"],
            ["brand_id" => 5, "name" => "Accent"],
            ["brand_id" => 5, "name" => "Sonata"],
            ["brand_id" => 5, "name" => "Tucson"],
            ["brand_id" => 5, "name" => "i10"],
            ["brand_id" => 5, "name" => "120"],
            ["brand_id" => 5, "name" => "i30"],
            ["brand_id" => 5, "name" => "Kona"],
            ["brand_id" => 5, "name" => "Bayon"],
            ["brand_id" => 5, "name" => "Ioniq 5"],
            ["brand_id" => 6, "name" => "Fiesta"],
            ["brand_id" => 6, "name" => "Focus"],
            ["brand_id" => 6, "name" => "Mustang"],
            ["brand_id" => 6, "name" => "Kuga"],
            ["brand_id" => 6, "name" => "Ranger"],
            ["brand_id" => 6, "name" => "Transit"],
            ["brand_id" => 6, "name" => "Tourneo"],
            ["brand_id" => 6, "name" => "Mondeo"],
            ["brand_id" => 6, "name" => "Explorer"],
            ["brand_id" => 6, "name" => "Edge"],
            ["brand_id" => 7, "name" => "Corolla"],
            ["brand_id" => 7, "name" => "Yaris"],
            ["brand_id" => 7, "name" => "C-HR"],
            ["brand_id" => 7, "name" => "Hilux"],
            ["brand_id" => 7, "name" => "Auris"],
            ["brand_id" => 7, "name" => "Avensis"],
            ["brand_id" => 7, "name" => "Camry"],
            ["brand_id" => 7, "name" => "Land Cruiser"],
            ["brand_id" => 7, "name" => "Supra"],
            ["brand_id" => 7, "name" => "Prius"],
            ["brand_id" => 8, "name" => "208"],
            ["brand_id" => 8, "name" => "308"],
            ["brand_id" => 8, "name" => "408"],
            ["brand_id" => 8, "name" => "508"],
            ["brand_id" => 8, "name" => "2008"],
            ["brand_id" => 8, "name" => "3008"],
            ["brand_id" => 8, "name" => "5008"],
            ["brand_id" => 8, "name" => "Rifter"],
            ["brand_id" => 8, "name" => "Partner"],
            ["brand_id" => 8, "name" => "Expert"],
            ["brand_id" => 9, "name" => "Civic"],
            ["brand_id" => 9, "name" => "CR-V"],
            ["brand_id" => 9, "name" => "HR-V"],
            ["brand_id" => 9, "name" => "Jazz"],
            ["brand_id" => 9, "name" => "Accord"],
            ["brand_id" => 9, "name" => "City"],
            ["brand_id" => 9, "name" => "Insight"],
            ["brand_id" => 9, "name" => "Odyssey"],
            ["brand_id" => 9, "name" => "ZR-V"],
            ["brand_id" => 9, "name" => "Civic Type R"],
            ["brand_id" => 10, "name" => "XC40"],
            ["brand_id" => 10, "name" => "XC60"],
            ["brand_id" => 10, "name" => "XC90"],
            ["brand_id" => 10, "name" => "S60"],
            ["brand_id" => 10, "name" => "S90"],
            ["brand_id" => 10, "name" => "V40"],
            ["brand_id" => 10, "name" => "V60"],
            ["brand_id" => 10, "name" => "V90"],
            ["brand_id" => 10, "name" => "V60 Cross"],
            ["brand_id" => 10, "name" => "V90 Cross"],
        ];

        DB::table('car_models')->insert($models);
    }
}
